補充兩岸讀音相異的單字 #37
rime/rime-terra-pinyin pull request #38
Opened 2021-09-11 03:34 UTC by dqwyy

2021-09-11 11:31 UTC, dqwyy commented
第二筆「小修改」本來想刪除打多出一行的`危 wei2`，以及改一下日期，結果新舊文件之間無法正常顯示出版本差異了，勞煩管理員幫忙了

2021-09-11 14:27 UTC, LEOYoon-Tsaw commented
你可以撤銷(revert)第二次commit

2021-09-11 15:36 UTC, dqwyy commented
謝謝，我發現網頁版無法執行這個操作，下載了Windows版操作，應該是成功了

2021-09-13 05:14 UTC, lotem requested changes
感謝拾柴。
需要關注對多音字權重的處理。
還一個盲區，只看代碼的差異不夠，需要在整個詞庫裏檢查：
如果添加字音後，某個字變成了多音字，這個字還出現在多音詞的注音裏面，則該詞的注音也需要增加標註。

舉一個例子。假設詞庫有
```
僞作	wei3 zuo4
```
因爲「作」是多音字，有 zuo1, zuo2, zuo4 等。
原有詞條的註音是爲了對「作」的讀音消歧，使程序不會自動推導出其他單字音的組合。
現在「僞」增加了一個常用讀音 wei4，需要同時定義
```
僞作	wei3 zuo4
僞作	wei4 zuo4
```
很遺憾，這種情況目前還需要人工審查保證改動完整。

2021-09-18 13:38 UTC, dqwyy commented on terra_pinyin.dict.yaml
> +昔	cuo4
權重剛剛已經修改了，這方面我確實不太懂，感謝指點。

2021-09-20 15:12 UTC, dqwyy commented
至於多音字消歧，我應該力不足了，一個一個弄工作量有點大 #32 不知道能否自動化

2021-09-23 09:51 UTC, lotem commented
​感謝。
等我想想辦法。

2021-11-20 18:34 UTC, ShikiSuen commented
我剛剛給新酷音新增了全字庫讀音支援：
https://github.com/rime/rime-terra-pinyin/pull/42

不過我也只是針對單字讀音而已。詞組讀音恐需要長期調整。
八股文會讓所有有問題的義項更容易破相。

2023-10-03 01:00 UTC, closed without merging