补充全字库汉字、补充来自新酷音与雅虎注音与小麦注音的单字读音
rime/rime-terra-pinyin pull request #42
Opened 2021-11-20 18:30 UTC by ShikiSuen

直接用汉字读音的话应该不要紧，毕竟他们也都是使用台澎金马地区官方公开的音韵库+他们平时通用的一些其他读法。
倒是词库的话就只能根据八股文在新词面前破相的表现来慢慢调整了。

P.S.: 这样一来 RIME 地球拼音与注音就支持全字库了，总共支持十万零七千多字喔。

2021-11-20 18:31 UTC, ShikiSuen commented
喔幹，我忘記將增補漢字當中的臺灣字轉成香港字了。回頭慢慢來。

2021-11-21 11:46 UTC, ShikiSuen commented
已经融入新酷音与小麦注音的词语音韵库。雅虎注音的词库没能弄到，就没考虑。
单字读音库与词语音韵库被我拆开了，方便维护。
目前正在想办法生成新的八股文。

2021-11-21 15:16 UTC, ShikiSuen commented
八股文搞定了：https://github.com/rime/rime-essay/pull/24

2021-11-23 15:57 UTC, ShikiSuen commented
这 PR 先别急着通过。我将基础词库又重新弄了。
新的单字读音数据来源自通用规范汉字表与：https://data.gov.tw/dataset/5961
這樣在單字讀音方面就不用以小麥注音與雅虎注音為中心了。
通用规范汉字表及對應繁體字的單字的優先權重會弄得高一些，免得候選詞順序一團糟。

2021-11-23 16:37 UTC, ShikiSuen commented
这次的词库内容是用这个脚本洗过的、以满足佛振的要求。
[CONV-TW2TERRA.SED.txt](https://github.com/rime/rime-terra-pinyin/files/7589622/CONV-TW2TERRA.SED.txt)
但是，在此之上的其他用于扩展 CNS11643 的字不会用这个脚本来清洗……
只是会被降权到 3% 以下，否则候选字顺序会大乱。（4% 是给简化字用的。）
宗旨是能用这套词库输入全字库 CNS11643 所有的汉字。

2022-02-15 13:45 UTC, nimser requested changes
還有這些沒改的：
![image](https://user-images.githubusercontent.com/634808/154074251-dd66d2a9-45bb-4f74-9bd8-e899c08c6572.png)

2022-02-15 15:16 UTC, ShikiSuen commented
@nimser 我沒在維護這個了。
佛振對 RIME 官方倉庫及內建語料庫主張康熙傳統繁體中文（而非台澎金馬繁體中文）。

如果您有相關需求的話，可以臉書搜尋 RIME-TW 使用他們針對台澎金馬繁體中文做過相容處理的版本。
如果您有在用 Windows 的話，PIME 新酷音安裝包也會隨贈 RIME 的 PIME 版本、裡面的語料庫可能是 RIME-TW 的版本。

2023-10-03 05:59 UTC, closed without merging